# Generated by Django 3.2 on 2022-11-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='watch_size',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
